// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7txXoRnzc09jUskP0RsQMeOMJtxN0ri0',
    appId: '1:166941519615:web:b4a013e8b03b892dea66ca',
    messagingSenderId: '166941519615',
    projectId: 'lastflutterproject',
    authDomain: 'lastflutterproject.firebaseapp.com',
    storageBucket: 'lastflutterproject.firebasestorage.app',
    measurementId: 'G-47MV42FTJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb9gDLqokifK8BBSnIxjzZ6-_J4Pr3-Pg',
    appId: '1:166941519615:android:b49670540934da90ea66ca',
    messagingSenderId: '166941519615',
    projectId: 'lastflutterproject',
    storageBucket: 'lastflutterproject.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7txXoRnzc09jUskP0RsQMeOMJtxN0ri0',
    appId: '1:166941519615:web:e998668a0c903c62ea66ca',
    messagingSenderId: '166941519615',
    projectId: 'lastflutterproject',
    authDomain: 'lastflutterproject.firebaseapp.com',
    storageBucket: 'lastflutterproject.firebasestorage.app',
    measurementId: 'G-CMTWF41MF0',
  );
}
