// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDojpc8QskfhWD-TXizeUBw4AQJ4EF2nGk',
    appId: '1:988838768989:web:8b7a4e645fc1b4249e38b4',
    messagingSenderId: '988838768989',
    projectId: 'restaurant-reviews-app-e7a11',
    authDomain: 'restaurant-reviews-app-e7a11.firebaseapp.com',
    storageBucket: 'restaurant-reviews-app-e7a11.firebasestorage.app',
    measurementId: 'G-P550FNS0SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz3bO39bW9qQlDQera8L-ySVhub2FbhEA',
    appId: '1:988838768989:android:6801323c921e3b079e38b4',
    messagingSenderId: '988838768989',
    projectId: 'restaurant-reviews-app-e7a11',
    storageBucket: 'restaurant-reviews-app-e7a11.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDojpc8QskfhWD-TXizeUBw4AQJ4EF2nGk',
    appId: '1:988838768989:web:098b076692564ab59e38b4',
    messagingSenderId: '988838768989',
    projectId: 'restaurant-reviews-app-e7a11',
    authDomain: 'restaurant-reviews-app-e7a11.firebaseapp.com',
    storageBucket: 'restaurant-reviews-app-e7a11.firebasestorage.app',
    measurementId: 'G-5KT5T9R27L',
  );
}
